name: build-and-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies (./cdk)
        run: npm ci
        working-directory: cdk
      - name: Install Dependencies (./lambda)
        run: npm ci
        working-directory: lambda
      - name: Test
        run: npm t
        working-directory: lambda
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Configure AWS Credentials
        if: startsWith(github.ref, 'refs/heads/main')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: AlexaItteqPrefetch
      - name: Deploy
        if: startsWith(github.ref, 'refs/heads/main')
        run: npm run cdk -- deploy -c stage=Prod --require-approval never
        working-directory: cdk
